services:
  client:
    build:
      context: .
      target: runner
    restart: unless-stopped
    env_file: .env.development.local
    volumes:
      - .:/client
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      MONGO_USERNAME: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASS
      NODE_ENV: development
    networks:
      - app-network

  database:
    image: mongo:latest
    restart: unless-stopped
    env_file: .env.development.local
    volumes:
      - ./mongo:/var/lib/mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    networks:
      - app-network

networks:
  app-network: {}

volumes:
  mongo: