export const routes = {
  faq: '/faq',
  login: '/sign-in',
  aboutUs: '/about_us',
  contacts: '/contacts',
  admin: '/admin/create',
  registration: '/sign-up',
  boards: '/manager/boards',
  requests: '/admin/requests',
  declined: '/admin/declined',
  aboutService: '/about_service',
  employees: '/manager/employees',
  organizations: '/admin/organizations',
  passwordChange: '/manager/password-change',
};
