export { default as default } from './default.png';
export { default as drohomyretskaAnastasiia } from './drohomyretskaAnastasiia.jpg';
export { default as hladchenkoAnatolii } from './hladchenkoAnatolii.jpg';
export { default as ivanishchevaAlina } from './ivanishchevaAlina.jpg';
export { default as kostyriaVladyslav } from './kostyriaVladyslav.jpg';
export { default as kyrychenkoRoman } from './kyrychenkoRoman.png';
export { default as kyslytsiaDenys } from './kyslytsiaDenys.jpg';
export { default as pupkovaKateryna } from './pupkovaKateryna.jpg';
export { default as voronkoSerhii } from './voronkoSerhii.jpg';
