export { default as UA } from './ua.svg';
export { default as EN } from './en.svg';
export { default as Eye } from './eye.svg';
export { default as EyeOff } from './eye-off.svg';
export { default as Warning } from './warning.svg';
export { default as Info } from './info.svg';
export { default as Logo } from './logo.svg';
export { default as Search } from './search.svg';
export { default as Close } from './input-close.svg';
export { default as Clip } from './clip.svg';
export * as DashboardIcon from './dashboard';
