import Image from 'next/image';

import { MRT_Row } from 'material-react-table';

import { Person } from '.';
import { BannerContacts, EmptyPhoto } from '@/assets/img';

export const header = [
  {
    accessorKey: 'number',
    size: 50,
    header: '№',
    enableSorting: false,
    enableColumnFilter: false,
    enableEditing: false,
  },
  {
    size: 150,
    accessorKey: 'id',
    header: 'ID номер',
    enableSorting: false,
    enableColumnFilter: false,
    enableEditing: false,
  },
  {
    size: 150,
    header: 'Фото',
    accessorKey: 'photo',
    enableColumnFilter: false,
    Cell: ({ row }: { row: MRT_Row<Person> }) =>
      row.original.photo ? (
        <Image src={row.original.photo} alt="Profile" width={125} height={85} style={{ objectFit: 'cover' }} />
      ) : (
        <Image src={EmptyPhoto} alt="Profile" width={85} height={85} style={{ objectFit: 'cover', margin: 'auto' }} />
      ),
  },
  {
    enableHiding: false,
    accessorKey: 'name',
    header: 'Назва',
    size: 200,
    enableColumnFilter: false,
  },
  {
    accessorKey: 'category',
    header: 'Категорія',
    size: 200,
    filterVariant: 'select' as const,
    filterSelectOptions: [
      { text: 'Категорія 1', value: 'Категорія 1' },
      { text: 'Категорія 2', value: 'Категорія 2' },
      { text: 'Категорія 3', value: '	Категорія 3' },
    ],
    filterFn: 'equals',
  },
  {
    accessorKey: 'unit',
    header: 'Одиниця вимірювання',
    size: 250,
    enableSorting: false,
    enableColumnFilter: false,
  },
  {
    accessorKey: 'save',
    header: 'Поверх зберігання',
    size: 220,
    enableSorting: false,
  },
  {
    accessorKey: 'save_place',
    header: 'Місце зберігання',
    size: 220,
    enableSorting: false,
    filterVariant: 'select' as const,
    filterSelectOptions: [
      { text: '	Місце зберігання 1', value: '	Місце зберігання 1' },
      { text: 'Місце зберігання 2', value: '	Місце зберігання 2' },
      { text: 'Місце зберігання 3', value: '	Місце зберігання 3' },
      { text: 'Місце зберігання 4', value: 'Місце зберігання 4' },
    ],
    filterFn: 'equals',
  },
  {
    accessorKey: 'origin',
    header: 'Походження',
    size: 180,
    enableSorting: false,
    enableColumnFilter: false,
  },
  {
    accessorKey: 'financing',
    header: 'Фінансування',
    size: 180,
    enableSorting: false,
    enableColumnFilter: false,
  },
  {
    accessorKey: 'arrival_date',
    header: 'Дата надходження',
    size: 220,
    enableSorting: false,
    enableColumnFilter: false,
    enableEditing: false,
  },
  {
    accessorKey: 'price',
    header: 'Вартість',
    size: 150,
  },
  {
    accessorKey: 'created_at',
    header: 'Дата додавання',
    size: 220,
    enableSorting: false,
    enableColumnFilter: false,
    enableEditing: false,
  },
  {
    accessorKey: 'updated_at',
    header: 'Дата останньої зміни',
    size: 250,
    enableEditing: false,
  },
  {
    accessorKey: 'description',
    header: 'Опис',
    size: 250,
    enableSorting: false,
    enableColumnFilter: false,
  },
];

export const data = [
  {
    number: 1,
    id: 1124,
    photo: BannerContacts,
    name: 'Назва 1',
    category: 'Категорія 1',
    unit: 'Одиниця вимірювання 1',
    save: 'Поверх зберігання 1',
    save_place: 'Місце зберігання 2',
    origin: 'Походження 1',
    financing: 'Фінансування 1',
    arrival_date: '2023-01-01',
    price: 200,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 1',
  },
  {
    number: 2,
    id: 223534,
    photo: BannerContacts,
    name: 'Назва 2',
    category: 'Категорія 2',
    unit: 'Одиниця вимірювання 2',
    save: 'Поверх зберігання 2',
    save_place: 'Місце зберігання 2',
    origin: 'Походження 2',
    financing: 'Фінансування 2',
    arrival_date: '2023-01-01',
    price: 200,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 2',
  },
  {
    number: 3,
    id: 343654,
    photo: BannerContacts,
    name: 'Назва 3',
    category: 'Категорія 3',
    unit: 'Одиниця вимірювання 3',
    save: 'Поверх зберігання 3',
    save_place: 'Місце зберігання 1',
    origin: 'Походження 3',
    financing: 'Фінансування 3',
    arrival_date: '2023-01-01',
    price: 1100,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 3',
  },
  {
    number: 4,
    id: 434343,
    photo: BannerContacts,
    name: 'Назва 4',
    category: 'Категорія 1',
    unit: 'Одиниця вимірювання 4',
    save: 'Поверх зберігання 4',
    save_place: 'Місце зберігання 4',
    origin: 'Походження 4',
    financing: 'Фінансування 4',
    arrival_date: '2023-01-01',
    price: 1100,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 4',
  },
  {
    number: 5,
    id: 598779,
    photo: BannerContacts,
    name: 'Назва 5',
    category: 'Категорія 2',
    unit: 'Одиниця вимірювання 5',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 1',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 100,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 5',
  },
  {
    number: 6,
    id: 598779,
    photo: BannerContacts,
    name: 'Назва 6',
    category: 'Категорія 3',
    unit: 'Одиниця вимірювання 6',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 3',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 1100,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 5',
  },
  {
    number: 7,
    id: 598779,
    photo: '',
    name: 'Назва 7',
    category: 'Категорія 1',
    unit: 'Одиниця вимірювання 7',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 4',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 11300,
    created_at: '2023-01-01',
    updated_at: '2025-25-25',
    description: 'Опис 5',
  },
  {
    number: 8,
    id: 598779,
    photo: '',
    name: 'Назва 8',
    category: 'Категорія 2',
    unit: 'Одиниця вимірювання 7',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 4',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 100,
    created_at: '2023-01-01',
    updated_at: '2025-25-25',
    description: 'Опис 5',
  },
  {
    number: 9,
    id: 598779,
    photo: BannerContacts,
    name: 'Назва 9',
    category: 'Категорія 2',
    unit: 'Одиниця вимірювання 7',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 2',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 1300,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 5',
  },
  {
    number: 10,
    id: 598779,
    photo: BannerContacts,
    name: 'Назва 10',
    category: 'Категорія 1',
    unit: 'Одиниця вимірювання 7',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 2',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 100,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 5',
  },
  {
    number: 11,
    id: 598779,
    photo: BannerContacts,
    name: 'Назва 11',
    category: 'Категорія 1',
    unit: 'Одиниця вимірювання 7',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 4',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 1300,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 5',
  },
  {
    number: 12,
    id: 598779,
    photo: BannerContacts,
    name: 'Назва 12',
    category: 'Категорія 3',
    unit: 'Одиниця вимірювання 7',
    save: 'Поверх зберігання 5',
    save_place: 'Місце зберігання 4',
    origin: 'Походження 5',
    financing: 'Фінансування 5',
    arrival_date: '2023-01-01',
    price: 1300,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    description: 'Опис 5',
  },
];
