name: "CodeQL - UI analysis"

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - '!client/.next'
      - '!client/coverage'
      - '!client/node_modules'
      - '!documentation'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/**'
      - '!client/.next'
      - '!client/coverage'
      - '!client/node_modules'
      - '!documentation'

jobs:
  deploy-ui:
    uses: it-volunteers-ukraine/ChariERP/.github/workflows/codeql-analysis.yml@main
    with:
      working-directory: ./client
