name: Deploy UI to Digital Ocean

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy-ui:
    uses: ./.github/workflows/digitalocean-deploy.yml
    with:
      working-directory: ./client
      container-name: chari_erp_ui
      do-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      telegram-to: ${{ secrets.TELEGRAM_TO }}
      telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
    permissions:
      id-token: write
      contents: read
