name: Deploy BE to Digital Ocean

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      environment:
        description: 'Environment to deploy to (e.g., production, staging)'
        required: true
        default: 'production'

jobs:
  deploy-ui:
    uses: ./.github/workflows/digitalocean-deploy.yml
    with:
      working-directory: ./server
      container-name: chari_erp_be
    secrets:
      do-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      telegram-to: ${{ secrets.TELEGRAM_TO }}
      telegram-token: ${{ secrets.TELEGRAM_TOKEN }}
    permissions:
      id-token: write
      contents: read
